name: math-course-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - ipykernel
  - pymc
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - arviz
  - pandas
